### PR TITLE
uwsgi.ini: change `socket` to `http-socket`

### PR DESCRIPTION
**Pull request by jps3**
Changing uwsgi.ini config file line from `socket = :8089`
to`http-socket = :8089` prevents constant error message `invalid
request block size: 21573 (max 4096)...skip` (as seen when using
command`docker logs -f margarita`), which prevented service from
working.

### CODE REVIEW

**Comment by jps3** [comment]
To add a little clarity: While `docker build ..` would work without error, and `docker run ...` would also, the service would not return and content, and `docker logs ...` would (after the initial startup output) list the `invalid request block size: 21573 (max 4096)...skip` for every request sent to the service. When I changed the `uwsgi.ini` file’s line from `socket ...` to `http-socket ...` then it worked fine. I am not sure what the basis for the error was, except perhaps some recent change to Flask?

Not sure if anyone else was running into this, but wanted to help out if I could.

**Comment by erlend** [comment]
The socket config is used when running behind another webserver (like nginx). Perhaps the best solution is to have the user select this with the command attribute.

I originally forked another repo, and need to make some changes to the readme as well. 

I'm currently on vacation, so i apologize if my responses are a bit late.

**Comment by jps3** [comment]
No rush, no worries. I did jump in quickly when I am not deeply familiar with uwsgi, so I apologize for any confusion or extra work. (My enthusiasm got away with me.) :-)

**Comment by erlend** [comment]
Just made some changes allowing you to specify http-socket in CMD. Running with `docker run -p 8089:8089 erlend/margarita --processes 4 --workers 2 --http-socket :8089` should now work without a webserver.

**Pull request closed without merging**
